# .zshrc

export PATH="/opt/homebrew/bin:$PATH"


# https://oliverspryn.com/blog/adding-git-completion-to-zsh
fpath=(/opt/homebrew/share/zsh/site-functions $fpath)

autoload -Uz compinit && compinit

setopt appendhistory
HISTFILE="/Users/jamesladd/.zsh_history"
HISTSIZE=99999999
HISTFILESIZE=99999999
